### ISSUE TITLE
MagePal_Core setup_version is not defined

### ISSUE THREAD

**Issue by macsanta** [magepal/magento2-core#1]
Error during bin/magento setup:upgrade
MagePal_Core setup_version is not defined in magepal/magento2-core/etc/module.xml

**Comment by brosenberger** [comment]
> Error during bin/magento setup:upgrade
> MagePal_Core setup_version is not defined in magepal/magento2-core/etc/module.xml

without that setup-version all magneto2 2.2 installation will not work

**Comment by srenon** [comment]
@brosenberger @macsanta .... this is now fixed... sorry about that
