### ISSUE TITLE
adminhtml panel sortorder

### ISSUE THREAD

**Issue by posidonius** [magepal/magento2-core#2]
Please be nice to your users and use a large sort order so your panel comes at the end of the default Magento sections in Configuration. Something like this in system.xml would be less intrusive:

`<tab id="magepal" translate="label" sortOrder="9999999" class="admin__page-magepal-tab">`

**Comment by srenon** [comment]
@posidonius ... there is a new setting to control the update badge

![image](https://user-images.githubusercontent.com/1415141/87350308-ad4a2200-c525-11ea-9760-01f89e53da5c.png)
