### ISSUE TITLE
Backwards compatibility 

### ISSUE THREAD

**Issue by MarianMates** [magepal/magento2-core#3]
magepal/magento2-core became required by magepal/magento2-googletagmanager and now setup:di:compile fails for older Magento 2 versions because of MagePal\Core\Controller\Adminhtml\Version\Index::ADMIN_RESOURCE .
The constant is declared as public, but PHP versions older than 7.1 do not support visibility modifiers for class constants. 
Could the visibility be removed, as it is public by default ?

**Comment by srenon** [comment]
@MarianMates ...Fixed... thanks for reporting this.
